# Generated by Django 3.2.16 on 2022-11-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("2", "High"), ("3", "Medium"), ("4", "Low"), ("1", "Urgent")],
                default="4",
                max_length=1,
            ),
        ),
    ]
