# Generated by Django 3.2.16 on 2022-11-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20221116_1239"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "priority"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "Urgent"),
                    ("High", "High"),
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                ],
                max_length=6,
            ),
        ),
    ]
