# Generated by Django 3.2.16 on 2022-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_auto_20221117_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[("2", "High"), ("1", "Urgent"), ("3", "Medium"), ("4", "Low")]
            ),
        ),
    ]
