# Generated by Django 3.2.16 on 2022-11-29 14:44

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="image",
            field=models.ImageField(
                null=True, upload_to=apps.home.models.worker_image_file_path
            ),
        ),
    ]
