# Generated by Django 3.2.16 on 2022-11-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_worker_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='image',
            new_name='profile_image',
        ),
    ]
