from django.urls import path, re_path
from apps.home import views
from apps.home.views import (
    WorkerListView,
    WorkerDetailView,
    delete_worker,
    WorkerCreateView,
    change_task_status,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    assign_to_task,
    TaskUpdateView,
    delete_task,
    TaskTypeListView,
    delete_task_type,
    TaskTypeCreateView,
    PositionListView,
    PositionCreateView,
    TaskTypeUpdateView,
    PositionUpdateView,
    delete_position,
    ProfileUpdateView,
)

urlpatterns = [
    path("", views.index, name="home"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/delete/<int:pk>/", delete_worker, name="worker-delete"),
    path(
        "workers/<int:pk>/profile_update/",
        ProfileUpdateView.as_view(),
        name="profile-update",
    ),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path(
        "tasks/status/<int:pk1>/<int:pk2>/",
        change_task_status,
        name="change-task-status",
    ),
    path("tasks/assign/<int:pk>/", assign_to_task, name="assign-to-task"),
    path("tasks/delete/<int:pk>/", delete_task, name="task-delete"),
    path("tasktypes/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "tasktypes/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path("tasktypes/", TaskTypeListView.as_view(), name="task-type-list"),
    path("tasktypes/delete/<int:pk>/", delete_task_type, name="task-type-delete"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path("positions/<int:pk>/delete/", delete_position, name="position-delete"),
    # Matches any html file
    re_path(r"^.*\.*", views.pages, name="pages"),
]
